name: pixman
version: 0.46.4
url: https://www.cairographics.org/releases/pixman-0.46.4.tar.xz
sha256: a098c33924754ad43f981b740f6d576c70f9ed1006e12221b1845431ebce1239
dependencies:
  required:
    - gettext
    - glib
    - libffi
    - libiconv
    - libpng
    - mspcrt
    - pcre2
    - pkg-config
    - zlib
script: build.bat
