name: libevent
version: 2.1.12
url: https://github.com/libevent/libevent/archive/refs/tags/release-2.1.12-stable.tar.gz
sha256: 7180a979aaa7000e1264da484f712d403fcf7679b1e9212c4e3d09f5c93efc24
dependencies:
  required:
    - openssl
    - zlib
script: build.bat
