name: grpc
version: v1.76.0
url: https://github.com/grpc/grpc.git
recursive: true
depth: 1
dependencies:
  required:
    - abseil-cpp
    - c-ares
    - nasm
    - openssl
    - protobuf
    - re2
    - zlib
script: build.bat
