name: Imath
version: 3.1.12
url: https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.1.12.tar.gz
sha256: 8a1bc258f3149b5729c2f4f8ffd337c0e57f09096e4ba9784329f40c4a9035da
dependencies:
  required:
    - icu4c
    - libiconv
    - libxml2
    - llvm-project
    - mspcrt
    - pkg-config
    - xz
    - zlib
    - zstd
script: build.bat
