name: libidn2
version: 2.3.7
url: https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz
sha256: 4c21a791b610b9519b9d0e12b8097bf2f359b12f8dd92647611a929e6bfd7d64
dependencies:
  required:
    - gettext
    - libiconv
    - libunistring
script: build.sh
