name: DyLP
version: master
url: https://github.com/coin-or/DyLP.git
recursive: false
depth: 1
dependencies:
  required:
    - bzip2
    - CoinUtils
    - Data-Sample
    - Data-Netlib
    - Osi
    - lapack
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - zlib
script: build.sh
