name: Clp
version: master
url: https://github.com/coin-or/Clp.git
recursive: false
depth: 1
dependencies:
  required:
    - bzip2
    - CoinUtils
    - Data-Sample
    - Data-Netlib
    - lapack
    - Osi
    - readline
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - SuiteSparse
    - zlib
script: build.sh
