name: mesa
version: 25.3.4
url: https://archive.mesa3d.org/mesa-25.3.4.tar.xz
sha256: 3a0fc6ec070b45ae25dc2ccb5e52fae1d89141f7c39c4a91fe4eaa80dfff9deb
dependencies:
  required:
    - DirectX-Headers
    - freeglut
    - icu4c
    - libiconv
    - libxml2
    - libva
    - llvm-project
    - lua
    - mspcrt
    - pkg-config
    - SPIRV-Tools
    - winflexbison
    - zlib
    - zstd
script: build.bat
