name: SHOT
version: master
url: https://github.com/coin-or/SHOT.git
recursive: true
depth: 1
dependencies:
  required:
    - bzip2
    - Cbc
    - Cgl
    - Clp
    - CoinUtils
    - Ipopt
    - lapack
    - mspcrt
    - Osi
    - pkg-config
    - spral
    - SuiteSparse
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Metis
    - ThirdParty-Mumps
    - zlib
script: build.bat
