name: Cgl
version: master
url: https://github.com/coin-or/Cgl.git
recursive: false
depth: 1
dependencies:
  required:
    - bzip2
    - Clp
    - CoinUtils
    - Data-Sample
    - DyLP
    - lapack
    - Osi
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - Vol
    - zlib
script: build.sh
