name: libthai
version: 0.1.30
url: https://github.com/tlwg/libthai/archive/refs/tags/v0.1.30.tar.gz
sha256: d7d16c155d2f7561ba9eb1b2d8d68647f4ea0d870b5d2a26a5d421c8ed561667
dependencies:
  required:
    - libiconv
    - libdatrie
script: build.sh
