name: glslang
version: 16.2.0
url: https://github.com/KhronosGroup/glslang/archive/refs/tags/16.2.0.tar.gz
sha256: 01985335785c97906a91afe3cb5ee015997696181ec6c125bab5555602ba08e2
dependencies:
  required:
    - SPIRV-Tools
script: build.bat
