name: SYMPHONY
version: master
url: https://github.com/coin-or/SYMPHONY.git
recursive: false
depth: 1
dependencies:
  required:
    - bzip2
    - Cgl
    - Clp
    - CoinUtils
    - Data-Sample
    - Data-Netlib
    - Data-miplib3
    - DyLP
    - lapack
    - Osi
    - readline
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - Vol
    - zlib
script: build.sh
