name: pango
version: 1.56.4
url: https://download.gnome.org/sources/pango/1.56/pango-1.56.4.tar.xz
sha256: 17065e2fcc5f5a5bdbffc884c956bfc7c451a96e8c4fb2f8ad837c6413cb5a01
dependencies:
  required:
    - brotli
    - bzip2
    - cairo
    - expat
    - gettext
    - gi-docgen
    - gobject-introspection
    - glib
    - fontconfig
    - freetype
    - fribidi
    - harfbuzz
    - help2man
    - libdatrie
    - libffi
    - libiconv
    - libpng
    - libthai
    - mspcrt
    - pcre2
    - pixman
    - pkg-config
    - zlib
script: build.bat
