name: harfbuzz
version: 12.3.1
url: https://github.com/harfbuzz/harfbuzz/archive/refs/tags/12.3.1.tar.gz
sha256: b487c4fefc6bb199591b9f6b962a120df37895b5fe9daed923e00d3676d5c661
dependencies:
  required:
    - brotli
    - bzip2
    - expat
    - gettext
    - icu4c
    - libffi
    - libiconv
    - libpng
    - mspcrt
    - pcre2
    - pkg-config
    - zlib
  optional:
    - cairo
    - fontconfig
    - freetype
    - glib
    - gobject-introspection
    - pixman
script: build.bat
