name: gst-plugins-good
version: 1.27.90
url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.27.90.tar.xz
sha256: 6ae5c65ef3a00f0ca34d1bb8011be42240a590f8cd04690ad28d6fa331bc5f44
dependencies:
  required:
    - bzip2
    - expat
    - flac
    - fontconfig
    - freetype
    - gettext
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - gstreamer
    - gst-plugins-base
    - gtk3
    - libffi
    - libiconv
    - libjpeg-turbo
    - libogg
    - libpng
    - libRaw
    - libvpx
    - mspcrt
    - nasm
    - nettle
    - openssl
    - orc
    - pcre2
    - pixman
    - pkg-config
    - speex
    - zlib
script: build.bat
