name: gst-devtools
version: 1.27.90
url: https://gstreamer.freedesktop.org/src/gst-devtools/gst-devtools-1.27.90.tar.xz
sha256: bbee0e23d1680aee28ad6490a705efa93ad32fde07a418c013319126704fef09
dependencies:
  required:
    - brotli
    - bzip2
    - cairo
    - expat
    - fontconfig
    - freetype
    - fribidi
    - graphene
    - gdk-pixbuf
    - gettext
    - glib
    - gobject-introspection
    - gstreamer
    - gst-plugins-base
    - gst-plugins-bad
    - gst-rtsp-server
    - gtk3
    - harfbuzz
    - json-glib
    - libffi
    - libiconv
    - libpng
    - mspcrt
    - pango
    - pcre2
    - pkg-config
    - pixman
    - zlib
script: build.bat
