name: gst-plugins-ugly
version: 1.27.90
url: https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.27.90.tar.xz
sha256: 51514565c7864eec2d3e134439d42ec0a720e8d015436179abec9dca945522c5
dependencies:
  required:
    - a52dec
    - gettext
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - gstreamer
    - gst-plugins-base
    - libffi
    - libiconv
    - mspcrt
    - orc
    - pcre2
    - pkg-config
    - x264
    - zlib
script: build.bat
