name: eigen3
version: 3.4.1
url: https://gitlab.com/libeigen/eigen/-/archive/3.4.1/eigen-3.4.1.tar.bz2
sha256: 8bb7280b7551bf06418d11a9671fdf998cb927830cf21589b394382d26779821
dependencies:
  required:
    - ADOL-C
    - boost
    - fftw
    - sparsehash
    - gmp
    - gsl
    - METIS
    - mpfr
    - mpreal
    - OpenBLAS
    - mspcrt
    - pkg-config
    - SuiteSparse
    - superlu
    - sparsehash
script: build.bat
