name: glibmm
version: 2.86.0
url: https://download.gnome.org/sources/glibmm/2.86/glibmm-2.86.0.tar.xz
sha256: 39c0e9f6da046d679390774efdb9ad564436236736dc2f7825e614b2d4087826
dependencies:
  required:
    - gettext
    - glib
    - libffi
    - libiconv
    - libsigc++
    - mm-common
    - mspcrt
    - pcre2
    - pkg-config
    - zlib
script: build.bat
