name: PostgreSQL
version: 18.1
url: https://ftp.postgresql.org/pub/source/v18.1/postgresql-18.1.tar.bz2
sha256: ff86675c336c46e98ac991ebb306d1b67621ece1d06787beaade312c2c915d54
dependencies:
  required:
    - bzip2
    - curl
    - gettext
    - icu4c
    - krb5
    - libiconv
    - libidn2
    - libxml2
    - libxslt
    - llvm-project
    - lz4
    - mspcrt
    - ncurses
    - openssl
    - pcre
    - perl
    - pkg-config
    - readline
    - tcl
    - tk
    - xz
    - zlib
    - zstd
script: build.bat
