name: recode
version: master
url: https://github.com/rrthomas/recode.git
recursive: true
depth: 1
submodules:
  gnulib:
    url: https://github.com/coreutils/gnulib.git
    branch: master
dependencies:
  required:
    - gettext
    - libiconv
    - mspcrt
script: build.sh
