name: librsvg
version: 2.60.2
url: https://download.gnome.org/sources/librsvg/2.60/librsvg-2.60.2.tar.xz
sha256: a5363adab179340fe03bf7896cf416c87f81dde855c10e572613f634abbed460
dependencies:
  required:
    - brotli
    - bzip2
    - cairo
    - cargo-c
    - dav1d
    - expat
    - fontconfig
    - freetype
    - fribidi
    - gdk-pixbuf
    - gettext
    - gobject-introspection
    - glib
    - harfbuzz
    - icu4c
    - libavif
    - libdatrie
    - libffi
    - libiconv
    - libpng
    - libthai
    - libxml2
    - mspcrt
    - pango
    - pcre2
    - pixman
    - pkg-config
    - vala
    - xz
    - zlib
script: build.bat
