name: gobject-introspection
version: 1.86.0
url: https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/1.86.0/gobject-introspection-1.86.0.tar.bz2
sha256: cbe8498bae9a9f894d8ebf4c806bebbb3321f470c0ce452d661d3ee1ba168dc5
dependencies:
  required:
    - brotli
    - expat
    - fontconfig
    - gettext
    - glib:required
    - harfbuzz:required
    - libffi
    - libiconv
    - libpng
    - mspcrt
    - pcre2
    - pkg-config
    - winflexbison
    - zlib
  optional:
    - cairo
    - freetype
    - pixman
script: build.bat
