name: mumps
version: v5.8.2.0
url: https://github.com/scivision/mumps.git
recursive: true
depth: 1
dependencies:
  required:
    - icu4c
    - libiconv
    - libxml2
    - llvm-project
    - METIS
    - lapack
    - scalapack
    - scotch
    - winflexbison
    - xz
    - zlib
    - zstd
script: build.bat
