name: chromaprint
version: 1.5.1
url: https://github.com/acoustid/chromaprint/archive/refs/tags/v1.5.1.tar.gz
sha256: a1aad8fa3b8b18b78d3755b3767faff9abb67242e01b478ec9a64e190f335e1c
dependencies:
  required:
    - fftw
    - googletest
script: build.bat
