name: fluidsynth
version: 2.5.1
url: https://github.com/FluidSynth/fluidsynth/archive/refs/tags/v2.5.1.tar.gz
sha256: 10b2e32ba78c72ac1384965c66df06443a4bd0ab968dcafaf8fa17086001bf03
dependencies:
  required:
    - doxygen
    - gcem
    - gettext
    - glib
    - icu4c
    - libiconv
    - libsndfile
    - libxml2
    - libxslt
    - llvm-project
    - mspcrt
    - pcre
    - readline
    - SDL3
    - xz
    - zlib
    - zstd
script: build.bat
