name: CHiPPS-BiCePS
version: 0.94.9
url: https://github.com/coin-or/CHiPPS-BiCePS/archive/refs/tags/releases/0.94.9.tar.gz
sha256: 443dedad02bf982eb17f884d4dc38945673cd44da37d8497441a00a39320193d
dependencies:
  required:
    - BuildTools
    - bzip2
    - Cgl
    - CHiPPS-ALPS
    - Clp
    - CoinUtils
    - Data-Sample
    - lapack
    - Osi
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - zlib
script: build.sh
