name: Dip
version: 0.95.1
url: https://github.com/coin-or/Dip/archive/refs/tags/releases/0.95.1.tar.gz
sha256: 064deaaee854ad6cf865501cbfc8864c066ab9d8af9d15d4cbe0b4599782c6db
dependencies:
  required:
    - BuildTools
    - bzip2
    - Cbc
    - Cgl
    - Clp
    - CHiPPS-ALPS
    - CoinUtils
    - Data-Sample
    - lapack
    - Osi
    - SYMPHONY
    - ThirdParty-ASL
    - ThirdParty-Glpk
    - ThirdParty-Mumps
    - zlib
script: build.sh
