name: ccls
version: master
url: https://github.com/MaskRay/ccls.git
recursive: true
depth: 1
dependencies:
  required:
    - icu4c
    - libiconv
    - libxml2
    - llvm-project
    - mspcrt
    - RapidJSON
    - xz
    - zlib
    - zstd
script: build.bat
