name: vim
version: master
url: https://github.com/vim/vim.git
recursive: false
depth: 1
dependencies:
  required:
    - gettext
    - libiconv
    - libsodium
    - lua
    - perl
    - ruby
    - tcl
script: build.bat
