name: libxml++
version: 5.4.0
url: https://download.gnome.org/sources/libxml%2B%2B/5.4/libxml%2B%2B-5.4.0.tar.xz
sha256: e9a23c436686a94698d2138e6bcbaf849121d63bfa0f50dc34fefbfd79566848
dependencies:
  required:
    - icu4c
    - libiconv
    - libxml2
    - libxslt
    - mspcrt
    - pkg-config
    - xz
    - zlib
script: build.bat
